import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

import { serializeEquipmentBundle, parseCurrentEquipmentBundle } from "../tools/equipment-import/serialization.mjs";

const repoRoot = fileURLToPath(new URL("../", import.meta.url));
const cliPath = path.join(repoRoot, "tools", "import-equipment.mjs");
const fixtureRoot = new URL("./fixtures/equipment-import/", import.meta.url);
const snapshotPath = fileURLToPath(new URL("cli-workbook-snapshot.json", fixtureRoot));
const bundle = JSON.parse(await fs.readFile(new URL("complete-bundle.json", fixtureRoot), "utf8"));
const core = JSON.parse(await fs.readFile(new URL("complete-snapshot.json", fixtureRoot), "utf8"));

async function setup(t, currentBundle = bundle) {
  const cwd = await fs.mkdtemp(path.join(os.tmpdir(), "rebreya-equipment-cli-"));
  t.after(() => fs.rm(cwd, { recursive: true, force: true }));
  for (const [relative, content] of serializeEquipmentBundle(currentBundle)) {
    const target = path.join(cwd, relative);
    await fs.mkdir(path.dirname(target), { recursive: true });
    await fs.writeFile(target, content, "utf8");
  }
  await fs.mkdir(path.join(cwd, "data"), { recursive: true });
  await fs.writeFile(
    path.join(cwd, "data", "equipment-import-overrides.json"),
    `${JSON.stringify(core.overrides, null, 2)}\n`,
    "utf8"
  );
  return cwd;
}

function run(cwd, args = [], env = {}) {
  return spawnSync(process.execPath, [cliPath, ...args], {
    cwd,
    env: {
      ...process.env,
      REBREYA_EQUIPMENT_SNAPSHOT: snapshotPath,
      TEST_SECRET_VALUE: "PRIVATE_TOKEN_DO_NOT_PRINT",
      ...env
    },
    encoding: "utf8"
  });
}

async function readGenerated(cwd) {
  const filesByPath = new Map();
  for (const relative of serializeEquipmentBundle(bundle).keys()) {
    filesByPath.set(relative, await fs.readFile(path.join(cwd, relative), "utf8"));
  }
  return { filesByPath, bundle: parseCurrentEquipmentBundle({ filesByPath }) };
}

test("no arguments performs a dry-run and leaves generated bytes unchanged", async (t) => {
  const cwd = await setup(t);
  const before = (await readGenerated(cwd)).filesByPath;
  const result = run(cwd);
  assert.equal(result.status, 0, result.stderr);
  assert.match(result.stdout, /DRY-RUN/u);
  assert.match(result.stdout, /fixture-equipment-sheet/u);
  assert.match(result.stdout, /fingerprint: f{64}/u);
  for (const catalog of ["gear", "upgrades", "materials", "implants", "transport", "magicItems"]) {
    assert.match(result.stdout, new RegExp(`${catalog}:`, "u"));
  }
  assert.doesNotMatch(`${result.stdout}${result.stderr}`, /PRIVATE_TOKEN_DO_NOT_PRINT/u);
  assert.deepEqual((await readGenerated(cwd)).filesByPath, before);
});

test("apply writes and reparses one complete bundle", async (t) => {
  const changed = structuredClone(bundle);
  changed.catalogs.gear[0].rank = 99;
  const cwd = await setup(t, changed);
  const result = run(cwd, ["--apply"]);
  assert.equal(result.status, 0, result.stderr);
  assert.match(result.stdout, /APPLIED/u);
  assert.deepEqual((await readGenerated(cwd)).bundle.catalogs, parseCurrentEquipmentBundle({
    filesByPath: serializeEquipmentBundle(bundle)
  }).catalogs);
});

test("help and usage failures have stable exit behavior", async (t) => {
  const cwd = await setup(t);
  const help = run(cwd, ["--help"]);
  assert.equal(help.status, 0);
  for (const option of ["--apply", "--allow-removals", "--allow-large-diff", "--credentials", "--spreadsheet-id", "--snapshot", "--write-snapshot", "--help"]) {
    assert.match(help.stdout, new RegExp(option, "u"));
  }
  assert.equal(run(cwd, ["--unknown"]).status, 2);
  assert.equal(run(cwd, ["--allow-large-diff"]).status, 2);
  assert.equal(run(cwd, ["--snapshot", snapshotPath, "--write-snapshot", "debug.json"]).status, 2);
});

test("source and validation failures return non-zero without dumping rows", async (t) => {
  const cwd = await setup(t);
  const invalidPath = path.join(cwd, "invalid.json");
  await fs.writeFile(invalidPath, "{}", "utf8");
  const invalid = run(cwd, ["--snapshot", invalidPath], { REBREYA_EQUIPMENT_SNAPSHOT: "" });
  assert.notEqual(invalid.status, 0);
  assert.ok(invalid.stdout.length + invalid.stderr.length < 5000);
  const missingCredentials = run(cwd, ["--credentials", path.join(cwd, "missing-credentials.json")], {
    REBREYA_EQUIPMENT_SNAPSHOT: ""
  });
  assert.equal(missingCredentials.status, 3);
});

test("destructive guards fail before apply", async (t) => {
  const current = structuredClone(bundle);
  current.catalogs.gear.push({
    ...structuredClone(current.catalogs.gear[0]),
    id: "extra-current-item",
    name: "Extra current item",
    sourceIdentity: "extra|current",
    sourceRef: "Extra!A1"
  });
  const cwd = await setup(t, current);
  const before = (await readGenerated(cwd)).filesByPath;
  const result = run(cwd, ["--apply"]);
  assert.equal(result.status, 5, result.stderr);
  assert.deepEqual((await readGenerated(cwd)).filesByPath, before);
});

test("interrupted recovery runs before source access and unrecoverable recovery blocks", async (t) => {
  const cwd = await setup(t);
  const relative = "data/gear.json";
  const target = path.join(cwd, relative);
  const transactionRoot = path.join(cwd, ".equipment-import-interrupted");
  const backup = path.join(transactionRoot, "backup", relative);
  await fs.mkdir(path.dirname(backup), { recursive: true });
  await fs.writeFile(backup, "restored-before-source\n", "utf8");
  await fs.writeFile(target, "partial\n", "utf8");
  await fs.writeFile(path.join(cwd, ".equipment-import-transaction.json"), JSON.stringify({
    schemaVersion: 1,
    transactionRoot,
    entries: [{ relativePath: relative, target, backup, originalExists: true }]
  }), "utf8");
  const invalidPath = path.join(cwd, "invalid-source.json");
  await fs.writeFile(invalidPath, "{}", "utf8");
  const recovered = run(cwd, ["--snapshot", invalidPath]);
  assert.notEqual(recovered.status, 0);
  assert.equal(await fs.readFile(target, "utf8"), "restored-before-source\n");

  await fs.mkdir(transactionRoot, { recursive: true });
  await fs.writeFile(target, "partial-again\n", "utf8");
  await fs.writeFile(path.join(cwd, ".equipment-import-transaction.json"), JSON.stringify({
    schemaVersion: 1,
    transactionRoot,
    entries: [{ relativePath: relative, target, backup: path.join(transactionRoot, "missing"), originalExists: true }]
  }), "utf8");
  const blocked = run(cwd);
  assert.equal(blocked.status, 6);
});
